### ISSUE TITLE
Inline bs-blabla to the BuckleScript docs

### ISSUE THREAD

**Issue by ryyppy** [reason-association/reasonml.org#100]
BuckleScript needs a dedicated section for all its external decorators, such as `[@bs.module]`, with proper examples and more thorough explanation on its use-cases.

[bs-blabla](https://github.com/moroshko/bs-blabla) is probably the most complete documentation on all available decorators so far, so it would be great to process the material in a way so it's easy to navigate on the docs. (I asked the original author for permission, not sure if he still needs to add a license file though)

How to do this?
All bucklescript related information lives in the [pages/docs/reason-compiler/latest](https://github.com/reason-association/reasonml.org/tree/master/pages/docs/reason-compiler/latest) directory. The navigation can be extended in `layouts/ReasonCompilerDocsLayout.re`.

**Comment by fhammerschmidt** [comment]
I gladly would tackle this.

bs-blabla is probably not the most accurate name, though.

I would suggest to use **bs-decorators** instead for the doc title. Or do you have something better in mind?

**Comment by ryyppy** [comment]
Sure, give it a preferred name and place a link in the ReasonCompilerLayout in the Interop category maybe? There's also a reference to bs-blabla in there somewhere which needs to be redirected as well 👍

**Comment by ryyppy** [comment]
Done  🎉
