### ISSUE TITLE
Old mds files used + broken link

### ISSUE THREAD

**Issue by Et7f3** [reason-association/reasonml.org#105]
screenshot from reasonml.org: ![image](https://user-images.githubusercontent.com/29592775/74791657-5cf2cf00-52bb-11ea-9ada-b973d06eb45d.png)

and from reasonml.github.io: 
![image](https://user-images.githubusercontent.com/29592775/74791678-7562e980-52bb-11ea-9525-a246465bd20e.png)

Also I was able to trigger a 404 error when clicking on the `here` I thought https://github.com/reason-association/reasonml.org/commit/adef6f32d93defbbc40d96cf39467112580f599e helped to prevent that.

**Comment by ryyppy** [comment]
You just found a bug in the link rendering logic, thanks.

Right now, the markdown renderer is removing all occurrences of `.md(x)?$` in each link, this regex fails on anchored links, such as in this example: `/docs/.../object.md#tip-tricks`.

Will fix that

**Comment by ryyppy** [comment]
Tackling the old .md problem in #108
