### ISSUE TITLE
Blog section design

### ISSUE THREAD

**Issue by ryyppy** [reason-association/reasonml.org#127]
There's already a blog design, but we wanted to revisit it

**Comment by vmarcosp** [comment]
@ryyppy do you need help with some ui/ux issues? I can help :)

**Comment by ryyppy** [comment]
@vmarcosp woops, sorry for the late reply... design wise we are pretty tightly coupled to our designer here, so for the beginning there may be smaller components that are more isolated

**Comment by ryyppy** [comment]
Fixed with #135
