### ISSUE TITLE
ReasonML: Add list of reserved keywords

### ISSUE THREAD

**Issue by ryyppy** [reason-association/reasonml.org#13]
As discussed [here](https://reasonml.chat/t/is-there-a-list-of-reserved-words-for-reason-aka-reserved-keywords-identifiers/1213/4), it is a good idea to have a list of reserved keywords.

It would also be interesting to discuss certain syntax desugaring (such as `__x` for `first pipe placeholder` and `type_ vs. type` conversion in object attributes).

**Comment by yawaramin** [comment]
It was mentioned in the thread that OCaml docs already maintain a list of keywords: http://caml.inria.fr/pub/docs/manual-ocaml-312/manual044.html

It might make sense to maintain just a list of Reason _changes_ on top of that list. E.g., `private` -> `pri`, `match` -> `switch`, etc. Of course we would also point to the OCaml reserved words index and say something like, 'ReasonML reserved words are substantially the same as OCaml's, documented here: ... with the following changes: ...'

**Comment by ryyppy** [comment]
@yawaramin Is it bad to just copy paste it? I think it's better UX to have a complete list right inside the docs to prevent forwarding users to the OCaml manual (we can neither use OCaml nor Reason keywords for variable names, it would be great to have a total overview!)... I guess it's good for DRYness, but on the other hand, keywords won't change that often.

**Comment by yawaramin** [comment]
Copy-pasting with attribution and a link to the source should be fine. Although depending on how we want to show it in the Reason Association docs, it might not really be a straight copy-paste but rather a fairly complete re-organization of the index.

**Comment by amartincolby** [comment]
I'm of the mind that sending people outside of docs for other docs is bad practice. What needs to be known should exist in a single spot so it can be consumed, contemplated, and edited as a single creation. Reason is not OCaml.

**Comment by yawaramin** [comment]
@amartincolby I kind of refer to this as the 'curse of crossover technologies', you're always going to have to refer to something external :-)

That said, for the keyword list I agree it's a good idea to document it in one place since it's so intrinsic to Reason syntax.

**Comment by ryyppy** [comment]
We will find a way to make it a one page! @yawaramin I really like your argument about attribution, I still need to figure out all the license details for colocating information from different sources.

**Comment by amartincolby** [comment]
Considering that the list is purely informative, there is no copyright, so no legal need for attribution. One cannot copyright facts. I still think it a good idea to offer the attribution, though, since even though Reason and OCaml are not the same, understanding their similarities is important.

**Comment by mlms13** [comment]
There are some additional words in Reason that get special treatment (e.g. `not` gets rewritten as `!`) due to the fact that the parser makes some assumptions about the stdlib. I realize that's not quite the same thing as being a "reserved word" but it would be really great if those were documented somewhere.

**Comment by fhammerschmidt** [comment]
The correct list of keywords will always be in the source code: https://github.com/facebook/reason/blob/master/src/reason-parser/reason_declarative_lexer.mll#L85-L144

**Comment by ryyppy** [comment]
Fixed in #163
