### ISSUE TITLE
Add Belt version string in the docs

### ISSUE THREAD

**Issue by ryyppy** [reason-association/reasonml.org#14]
Not sure where to put this, but it would be great to keep track of the Belt version somewhere visible (maybe header?). I was thinking of retrieving the `bs-platform` version from our package.json for now.

**Comment by smlmrkhlms** [comment]
@ryyppy May I take a stab at this one?

**Comment by ryyppy** [comment]
sure! You could place it somewhere in the BeltDocLayout similar on how the design shows it:
https://xd.adobe.com/spec/15aaca36-8352-45aa-48c2-18fc508c81ed-639b/screen/64053c93-f30e-40d2-be46-e84cd63a5e4d/Belt-Desktop-wide

let me know if you have any questions 👍

**Comment by smlmrkhlms** [comment]
@ryyppy Sounds good!
