### ISSUE TITLE
BuckleScript into doesn't clarify much about what it is

### ISSUE THREAD

**Issue by davesnx** [reason-association/reasonml.org#152]
The intro lives here: https://reasonml.org/docs/reason-compiler/latest/introduction and looks like that:

```
BuckleScript isn't a new language. It simply takes OCaml, a fast, pragmatic and typed language, and makes it compile to clean, readable and performant JavaScript code. This allows the users to write in an industrial-strength language while using the existing, familiar JavaScript tools (npm/yarn, bundlers, minifiers, devtools, etc.) and accessing the vast ecosystem from both JavaScript and OCaml.

Thanks to its great interoperability with JS, BuckleScript can be seen as a "gradually" typed language, where you get to incrementally adopt it in your codebase file-by-file, while keeping the full benefits of a 100% sound and reliable type system, plus extra language features.
```

My honest suggestion:

I would keep the title "The Reason Compiler" and start with. It's called BuckleScript.

And then shuffle this ideas:

- Transpiles/Compiles Reason code to JavaScript (and other platforms as well)
- It's build in performance in mind. 
- Has great interoperability with JavaScript (and explain what interop means, in this case mention js bindings and `Js.` apis buildtin)
- Works per-file, so Incremental adoption is possible and very common.
- Maybe mention that comes from the OCaml compiler

**Comment by ryyppy** [comment]
This will be clarified with ReScript's new elevator pitch
