### ISSUE TITLE
Explain the `##` operator (or make the explanation easier to find if it exists)

### ISSUE THREAD

**Issue by sgrove** [reason-association/reasonml.org#168]
As per @jsjoeio in discord:

>  Follow up question: what is this operator called ##?

yawaramin: that's JavaScript property access
@anmonteiro linked to https://bucklescript.github.io/docs/en/object-2#accessors

> Ahh! Thank you @yawaramin and thanks for the link @anmonteiro ! I was looking on <reasonml.org>

**Comment by ryyppy** [comment]
Just to be clear, the same information is available on reasonml.org: https://reasonml.org/docs/reason-compiler/latest/object-2#accessors

I am not sure how to highlight the `##` syntax, except finally finding better names for the `Object` and `Object 2` pages. Any ideas on how to find it more easily are highly appreciated!

**Comment by jsjoeio** [comment]
A few thoughts that might help:

1. The search doesn't work on the site. In the idea world, I would search ## and be lead to this page on "Accessors"
<img width="144" alt="image" src="https://user-images.githubusercontent.com/3806031/81029030-69a5ae80-8e38-11ea-88f6-2b56bf82599e.png">
2. Add a description to "Accessors" - notice how it goes straight to "read" without telling me what it is or why I would use it
<img width="675" alt="image" src="https://user-images.githubusercontent.com/3806031/81029070-86da7d00-8e38-11ea-9ea7-8bb539d45769.png">
3. Yes I agree with you, we should find better names than `Object` and `Object 2` 😂 There has to be a name that is used to distinguish the two under the hood i.e. in the compiler right? One thought is to consolidate all the information from `Object` and `Object2` into one category called `Object`

**Comment by ryyppy** [comment]
Due to the move to ReScript, the `##` is obsolete and the `Object 2,..` section got refactored into a [unified object section](https://rescript-lang.org/docs/manual/v8.0.0/bind-to-js-object).
