### ISSUE TITLE
Document about pipe last and guide that it's usage is discouraged.

### ISSUE THREAD

**Issue by wontheone1** [reason-association/reasonml.org#177]
I learned that using pipe last operator (`|>`) is discouraged when compiling to JS.

Quoting @ryyppy 
> the conclusion for when to use pipe-first / pipe-last is: if you are using ocaml, you might want to use pipe-last, bc most apis are t-last. For bucklescript codebases, always use pipe-first, because it helps the compiler to eliminate runtime currying and it's also easier to map to JS apis due to their t-first nature

However, as long as this is legally compiled by the compiler, we still need to have documentation explains the syntax and why it is discouraged.

And other languages have both pipe operators too and users of those languages will start wondering what ReasonML pipe last operator looks like and waste time searching for it and they have to figure out in the wild internet about this syntax and they are discouraged. (e.g. in Clojure, both pipes are called thread macro and they don't have run time penalty and it's completely normal to use both)

**Comment by ryyppy** [comment]
Done!
