### ISSUE TITLE
Transfer Belt.List docs

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#2]
We transferred the names and type definitions, but explanations and examples are missing.

Current work: https://github.com/reason-association/reasonml.org/blob/master/pages/belt_docs/list.mdx

Belt List docs: https://bucklescript.github.io/bucklescript/api/Belt_List.html

Please comment on this issue if you would like to pick it up.

**Comment by lessp** [comment]
Happy to grab this! @nikgraf

**Comment by ryyppy** [comment]
Go for it @lessp 👍

**Comment by nikgraf** [comment]
already done, yay
