### ISSUE TITLE
Transfer Belt.Set docs

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#20]
We transferred the names and type definitions, but explanations and examples are missing.

Current work: https://github.com/reason-association/reasonml.org/blob/master/pages/belt_docs/set.mdx

Belt Set docs: https://bucklescript.github.io/bucklescript/api/Belt.Set.html

Please comment on this issue if you would like to pick it up.

**Comment by baransu** [comment]
Willing to help! :)
