### ISSUE TITLE
Playground "to be implemented"

### ISSUE THREAD

**Issue by MinimumViablePerson** [reason-association/reasonml.org#210]
https://reasonml.org/try just says "to be implemented" at the moment.

Is there any reason why it doesn't just take you here instead? https://reasonml.github.io/try

**Comment by ryyppy** [comment]
We didn't put any thought to a temporary solution here, so feel free to send a PR to add a link!

The new implementation of the playground is currently in the working and will hopefully be available soon.

**Comment by ryyppy** [comment]
implemented in rescript-lang!
