### ISSUE TITLE
Font hinting problems

### ISSUE THREAD

**Issue by lesha1201** [reason-association/reasonml.org#211]
# Description

There is a problem with font hinting for small thin text on Windows 10 (2560x1440) which makes text hard to read.

**From reasonml.org [Chrome 83]:**
![image](https://user-images.githubusercontent.com/10157660/84562394-fbb8a500-ad5c-11ea-8db9-c5b55f66a02a.png)

**Using official Inter font (for Web) [Chrome 83]:**
![image](https://user-images.githubusercontent.com/10157660/84562390-ecd1f280-ad5c-11ea-9d37-1a629b67aebd.png)

### Other examples of issue
**From reasonml.org:**
![image](https://user-images.githubusercontent.com/10157660/84562433-37536f00-ad5d-11ea-8b67-b75cecf58a53.png)
![image](https://user-images.githubusercontent.com/10157660/84562439-3de1e680-ad5d-11ea-88cb-6c89cef40d36.png)

# Solution

I've read that you used https://transfonter.org/ for subsettings the font. I've tried to upload the official font there and noticed that if hinting is set to `Keep existing` then it will generate a font with bad hinting but if to set to any other hinting then the generated font will be fine. I don't know why `Keep existing` is generating a font with bad hinting.

I think we need to either change parameters on https://transfonter.org/ or use other tools for subsetting. I can make PR but I need to know which glyphs are in the subset. Is it only Latin?

**Comment by ryyppy** [comment]
i think inter should be available via google fonts by now? maybe we should source the fontsets from there?

We are mostly using latin afaik to keep the size small

**Comment by lesha1201** [comment]
@ryyppy Yes, it's availabe on Google Fonts https://fonts.google.com/specimen/Inter . Also here is a good article about increasing performance for google fonts https://csswizardry.com/2020/05/the-fastest-google-fonts/
