### ISSUE TITLE
[Bucklescript] install via yarn fails with env: python: No such file or directory

### ISSUE THREAD

**Issue by serpent7776** [reason-association/reasonml.org#226]
Installing bucklescript via `yarn add --dev bs-platform` fails on building `ninja` with message `env: python: No such file or directory`

In fact on my machine, there's no `python` executable, only `python3`.

```
# yarn --version
1.22.4
```
```
# python3 --version
Python 3.7.8
```
```
# uname -a
FreeBSD DaemONX 11.4-RELEASE-p1 FreeBSD 11.4-RELEASE-p1 #0: Tue Jul  7 08:51:03 UTC 2020     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

[bs.log](https://github.com/reason-association/reasonml.org/files/4983996/bs.log)

**Comment by ryyppy** [comment]
Hey! This issue relates to the compiler toolchain. Could you open it up in the [BuckleScript](https://github.com/BuckleScript/bucklescript/issues) repo?

**Comment by serpent7776** [comment]
Created here https://github.com/BuckleScript/bucklescript/issues/4576

Maybe it would be a good idea to create an issue template with a link to the BuckleScript/bucklescript repo and note to report there in case of such issues. 

Thanks.
