### ISSUE TITLE
Fix broken examples

### ISSUE THREAD

**Issue by ryyppy** [reason-association/reasonml.org#29]
After #28 is merged, we should think about fixing the examples. 
Most of them are straightforward, such as correcting `map` to `Belt.Array.map` etc.

**Comment by nikgraf** [comment]
This is mostly related to it: https://github.com/reason-association/reasonml.org/issues/27

**Comment by fhammerschmidt** [comment]
I just fixed some of the examples (see #43 ): 
- [x] Array 
- [x] HashSet
- [x] List
- [x] Map

Still missing:
- [ ] Result
- [ ] Set
- [ ] Set.Dict
- [ ] Set.Int
- [ ] Set.String
- [ ] SortArray
- [ ] MutableSet
- [ ] MutableSet.Int
- [ ] MutableSet.String

**Comment by baransu** [comment]
`MutableSet`, `MutableSet.Int`, `MutableSet.String` and `Set`, `Set.Dict`, `Set.Int`, `Set.String` should be correct. I adjusted it during transfer.

**Comment by nikgraf** [comment]
@baransu we now have a test script automatically testing if all the examples compile: `yarn test`. Most of the ones you transferred do, but we can fix the ones which don't :)

**Comment by baransu** [comment]
@nikgraf I'll fix them as I have some time right now :)

**Comment by nikgraf** [comment]
@baransu awesome, I also started, but have to leave now. I merge this one: https://github.com/reason-association/reasonml.org/pull/47
