### ISSUE TITLE
Transfer Belt.Option docs

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#3]
We transferred the names and type definitions, but explanations and examples are missing.

Current work: https://github.com/reason-association/reasonml.org/blob/master/pages/belt_docs/option.mdx

Belt Option docs: https://bucklescript.github.io/bucklescript/api/Belt_Option.html

Please comment on this issue if you would like to pick it up.

**Comment by lessp** [comment]
Happy to start this @nikgraf, if no one has already! 🙂

**Comment by nikgraf** [comment]
@lessp go ahead! thanks a lot for doing so.

To your question: so far I just copied them exactly like in the original docs and fixed examples when I found broken ones. This also meant we followed their pattern of `sig`, usage, example. That said not all of them yet have a usage or an example.
No objection if you plan to extend or improve them :)
