### ISSUE TITLE
Transfer MapInt, MapString, MapDict Docs

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#36]
https://bucklescript.github.io/bucklescript/api/Belt_MapInt.html
https://bucklescript.github.io/bucklescript/api/Belt_MapString.html
https://bucklescript.github.io/bucklescript/api/Belt_MapDict.html

**Comment by sync** [comment]
example of what to do here: https://github.com/reason-association/reasonml.org/blob/master/pages/belt_docs/list.mdx

will look into it

**Comment by nikgraf** [comment]
thanks for doing so @sync 👏

**Comment by nikgraf** [comment]
@sync are you able to finish it this weekend? We would like to finish up this weekend with the transfer so people can start using it next week. No problem if you can't make it. I can take over and you could help with other things.

**Comment by sync** [comment]
Yes I was planning on doing this Friday night and or Saturday Australia time would this be fast enough?

**Comment by sync** [comment]
Basically means I’ll get this going right after work in about 10 hours

**Comment by nikgraf** [comment]
totally, thx a lot

**Comment by sync** [comment]
sorry for the delay starting this now, will open a draft pr as soon as i make some progress :-)

**Comment by sync** [comment]
@nikgraf have a look at this PR: https://github.com/reason-association/reasonml.org/pull/45 and let me know how it can be further improved
