### ISSUE TITLE
Create examples for every function of Option

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#54]
https://github.com/reason-association/reasonml.org/blob/master/pages/belt_docs/option.mdx

**Comment by smlmrkhlms** [comment]
@nikgraf I can take this one if it is okay with you.

**Comment by smlmrkhlms** [comment]
@nikgraf Actually, it seems like a lot of the examples are covered. Is the remaining work to be done providing examples for the uncurried versions or am I missing something? Thanks.

**Comment by nikgraf** [comment]
@smlmrkhlms I was thinking about uncurried examples, but we recently discussed to try out a section that generally explains uncurried functions. I will open issues for other Modules where we actually missing examples.

**Comment by smlmrkhlms** [comment]
@nikgraf Absolutely! Thanks.
