### ISSUE TITLE
Larger Click areas in the Sidebar

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#66]
Currently the click area is the size of the text. The smaller the text the harder it is to reach it easily.

<img width="860" alt="Screenshot 2019-10-18 at 12 30 02" src="https://user-images.githubusercontent.com/223045/67087455-43be0280-f1a3-11e9-89f4-ed3f52f15b80.png">

By applying `display: block` to the links the click area would be way larger.

<img width="935" alt="Screenshot 2019-10-18 at 12 30 17" src="https://user-images.githubusercontent.com/223045/67087486-520c1e80-f1a3-11e9-8c2f-de436625303f.png">

What do you think @bettistein @ryyppy?

**Comment by ryyppy** [comment]
I agree, maybe we can put a visual hover (simliar on how selected items look like, but more subtle) as well?

**Comment by nikgraf** [comment]
@ryyppy sounds good to me! Should I check with Betty or just implement it?

**Comment by bettistein** [comment]
@nikgraf @ryyppy Yes, that would be all great. (it was my initial idea anyway, but probably didn't communicate it through the design efficiently.)

**Comment by bettistein** [comment]
Please have a look on Nr. 8 in the comments: click area is transparent, but the appearance of the text changes on "hover". Let me know if that works. If it's too subtil, please tell me! 
https://xd.adobe.com/spec/15aaca36-8352-45aa-48c2-18fc508c81ed-639b/screen/5c8d88b2-5520-460f-aba5-e75d5d5413af/Belt-Desktop-lila-1

(sorry for the ugly link)

**Comment by ryyppy** [comment]
Will be solved in #84

**Comment by ryyppy** [comment]
Fixed
