### ISSUE TITLE
Long signatures are cut off

### ISSUE THREAD

**Issue by nikgraf** [reason-association/reasonml.org#80]
Currently long signatures don't fit and there is a horizontal scrollbar. For once sometimes it's not obvious that I can scroll and in general it's not a nice experience when trying to grasp the whole functions.

<img width="682" alt="Screenshot 2019-10-27 at 21 41 12" src="https://user-images.githubusercontent.com/223045/67641460-8e0d5500-f902-11e9-9dc6-82f3d2ce4a3c.png">

For wider screens to we really need to cut them off?
For smaller screens would could wrap them to the next line?
Any other ideas?

**Comment by nikgraf** [comment]
Just noticed it's the same for examples.

**Comment by bettistein** [comment]
I would go for "next line" rather than scrolling. Should I do a quick design for this? @ryyppy @nikgraf

**Comment by ryyppy** [comment]
@nikgraf I think for very long signatures, we need to set up `refmt` to limit it to a certain line length and let `refmt` do it's job. A browser-enforced line wrap would definitely look weird?

**Comment by nikgraf** [comment]
great point, that said for small screen e.g. mobile this won't work?!?

Would it make sense to do the refmt thing for our standard size and then apply this CSS to the pre-tag:

```css
white-space: pre-wrap;
word-wrap: break-word;
```

It would look like this

<img width="512" alt="Screenshot 2019-10-28 at 10 51 25" src="https://user-images.githubusercontent.com/223045/67668922-27735000-f971-11e9-85cd-a10995292919.png">

**Comment by ryyppy** [comment]
Will be tackled by #84

**Comment by ryyppy** [comment]
Fixed
