### ISSUE TITLE
Code blocks have redundant vertical scrollbar in Firefox

### ISSUE THREAD

**Issue by kadfak** [reason-association/reasonml.org#86]
For some reason some code blocks have a scrollbar, others don't.

<details><summary>Show image</summary>

![bug](https://user-images.githubusercontent.com/17338808/68476558-ac911b80-0233-11ea-98dd-59069d6acd9a.png)
</details>

**Comment by ryyppy** [comment]
Will eventually be resolved by #84

**Comment by ryyppy** [comment]
Should be fixed now
