### ISSUE TITLE
Firefox: cannot scroll down to the bottom of the sidebar 

### ISSUE THREAD

**Issue by tsnobip** [reason-association/reasonml.org#88]
I noticed that to get to the bottom of the sidebar on Firefox I have to scroll down to the bottom of the main page. You can see how the bottom of the sidebar is cropped in this screenshot from the 13" screen of my old macbook air. Works as intended on Chrome. Maybe something to keep in mind during #84 :)
![Capture d’écran 2019-11-21 à 00 08 37](https://user-images.githubusercontent.com/2479216/69286320-3dcc9e80-0bf3-11ea-9ed8-77bc1416afad.png)

**Comment by ryyppy** [comment]
Thanks for the report! Will make sure to fix that in the major design implementation in #84
