### ISSUE TITLE
Incorporate news aggregator?

### ISSUE THREAD

**Issue by fhammerschmidt** [reason-association/reasonml.org#89]
User @johnridesabike just announced his reason news aggregator in Discord.

https://github.com/johnridesabike/reason-planet
It currently aggregates blogposts from

- https://reasonml.github.io/blog/
- https://reasonml.github.io/reason-react/blog/
- https://bucklescript.github.io/blog/
- https://esy.sh/blog/

We think it would be an ideal fit for reasonml.org, as this site already aims to be the entry point for reason newcomers.

**Comment by ryyppy** [comment]
I hope we can just have one communication channel in the future... would make it much easier to have properly planned, scheduled and well-formatted content

**Comment by ryyppy** [comment]
Just to follow up to that, ideally this is how the blog section (with aggregated content) could look like:

![image](https://user-images.githubusercontent.com/1121889/74830072-a3274d00-5312-11ea-889a-ca4aa6d46dad.png)

Giving visual distinction and structure is something I really value in blogs (with proper highlights on the most important / most recent posts etc).

**Link to the design:** https://xd.adobe.com/spec/1cd19c3a-a0bb-4f93-4e11-725589888696-6ae0/screen/e26316a6-a350-4fd3-8331-629db3b945e6/Reason-1400-Blog

**Comment by ryyppy** [comment]
I'll consider this to be done for now, please reopen if there's anything missing!
