### ISSUE TITLE
The search window should be fixed

### ISSUE THREAD

**Issue by imbsky** [reason-association/reasonml.org#90]
Currently, when I moved from the top page to the API page, the search input position moves from right to left. This is little uncomfortable.

**Comment by ryyppy** [comment]
The search UI will be reworked in a later point in time. There's some UX testing we need to do first. For now #84 will remove the search bar in favor of a search icon

**Comment by ryyppy** [comment]
This issue is closed since the navigation has changed since then. Should be uniform right now

**Comment by imbsky** [comment]
Cool!
